In [1]:
import caf.base as cb
import pandas as pd

C:\Users\Predator\miniforge3\envs\tem\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [11]:
hb_prod_tem = cb.DVector.load(
    r"E:\tem\outputs\exp_seg\Core\hb_productions\hb_normits_tem_segmented_2023_dvec.h5"
)
# hb_notem = pd.read_csv(r"I:\NorMITs NoTEM\voa_gb_2023_uni\tripend\NorMITs_tripend_2023_hb_fr.csv.bz2", index_col=[0,1,2,3,4,5,6])#.unstack(level='normits_v3.3_id')

In [75]:
lookup = pd.read_csv(r"I:\NorMITs NoTEM\Inputs\normits_v3.3_lsoa21_trans.csv")

In [83]:
lookup[["normits_v3.3_id", "tfn_at"]].drop_duplicates().set_index("normits_v3.3_id")

                 tfn_at
normits_v3.3_id
7294002               1
2258001               5
2258002               5
2258003               5
2258004              14
...                 ...
3188005              19
3188023              19
2049064              17
2049029              17
2049065              17

[5431 rows x 1 columns]

In [95]:
trip_rates

,tfn_at,mode.hb,purpose.hb,mode,purpose,trips,trips.hb,gamma
0,1,1,1,1,1,78808.724580,847468.000100,0.042934
1,1,1,1,1,2,2975.446975,847468.000100,0.000742
2,1,1,1,1,3,2978.342246,847468.000100,0.000503
3,1,1,1,1,4,43330.355164,847468.000100,0.036216
4,1,1,1,1,5,18082.676234,847468.000100,0.002134
...,...,...,...,...,...,...,...,...
62715,20,7,8,7,4,0.000000,2433.888442,0.011049
62716,20,7,8,7,5,0.000000,2433.888442,0.000545
62717,20,7,8,7,6,1059.355634,2433.888442,0.003407
62718,20,7,8,7,7,0.000000,2433.888442,0.010600
62719,20,7,8,7,8,0.000000,2433.888442,0.004523

In [69]:
trip_rates = pd.read_csv(
    r"I:\NTS\outputs\productions\nhb\trip_rates\nhb_trip_rates_production.csv"
)

In [71]:
hb_notem_attr = (
    hb_notem.groupby(["normits_v3.3_id", "purpose", "mode"])["attr"]
    .sum()
    .unstack(level="normits_v3.3_id")
)

In [74]:
hb_notem_attr.head()

normits_v3.3_id     1001001      1001002       1001003      1001004   \
purpose mode
1       1         247.017861   347.853151   2906.241473   566.514031
        2          66.692139    94.209273    782.858541   151.863346
        3        1304.501177  1866.120741  15158.589197  2862.068314
        4          58.857851    84.237400    683.747357   129.085757
        5          82.155384   115.192554    969.632057   190.245631

normits_v3.3_id     1001005      1001006      1001007     1001008   \
purpose mode
1       1         204.244706   839.295166  1240.689063  127.184271
        2          55.610430   225.836831   333.445824   34.340458
        3        1125.666518  4342.494370  6385.887443  672.968854
        4          50.849412   195.890329   287.984800   30.358837
        5          67.134153   280.424401   415.224978   42.298033

normits_v3.3_id     1001009       1001010   ...      11357010     11358001  \
purpose mode                                ...
1       1         790.557395   2269.737459  ...   1804.465848   296.383081
        2         213.604098    612.176587  ...    190.717962    37.728723
        3        4190.001599  11932.881639  ...  10083.483789  1472.902993
        4         189.075912    538.273444  ...    496.505862   104.827195
        5         262.652306    755.973096  ...   1430.459679    41.230553

normits_v3.3_id      11358002      11358003      11358004      11358005  \
purpose mode
1       1        13298.684768  11748.069518   8000.702824   5658.789111
        2         1408.042843   1236.955059    841.181588    598.751180
        3        74814.832677  64563.497980  43661.967291  31745.910953
        4         3684.856807   3178.148728   2149.245301   1563.497337
        5        10519.957658   9353.510218   6379.845312   4479.774676

normits_v3.3_id       11358006      11358007      11358008       11358009
purpose mode
1       1         71123.096713   7201.572926   4002.281935   23759.591845
        2          7543.372650    759.164458    422.050910    2508.440985
        3        402802.328647  39749.856941  22164.888783  132078.782319
        4         19844.049106   1957.158164   1091.044126    6503.391357
        5         56145.944165   5725.287150   3181.294403   18857.682485

[5 rows x 5430 columns]

In [4]:
hb_prod_notem = (
    hb_notem["prod"]
    .groupby(level=["normits_v3.3_id", "purpose", "mode", "period"])
    .sum()
    .unstack(level="normits_v3.3_id")
)

In [5]:
hb_prod_notem

normits_v3.3_id        1001001     1001002     1001003     1001004   \
purpose mode period
1       1    1       717.154351  697.765969  681.917128  554.290639
             2       284.389991  285.804391  270.473171  217.127909
             3        14.970944   15.142488   14.130805   11.476851
             4       216.760691  286.564496  286.322126  232.142632
             5       100.564774  106.674774  103.674483   85.467914
...                         ...         ...         ...         ...
8       7    2         0.096241    0.096124    0.100592    0.072233
             3         0.103127    0.103001    0.107789    0.077401
             4         0.106936    0.106806    0.111770    0.080260
             5         0.077868    0.077773    0.081389    0.058443
             6         2.932365    1.131349    0.931706    0.906641

normits_v3.3_id        1001005     1001006     1001007     1001008   \
purpose mode period
1       1    1       542.492305  524.267029  394.823245  701.863012
             2       225.993964  212.475392  155.418055  276.641697
             3        12.165020   11.200963    8.207631   14.731449
             4       209.781867  191.001192  105.328393  293.551147
             5        82.274430   77.079075   54.003931  108.550293
...                         ...         ...         ...         ...
8       7    2         0.075442    0.073716    0.059810    0.096668
             3         0.080839    0.078990    0.064089    0.103584
             4         0.083825    0.081908    0.066457    0.107411
             5         0.061039    0.059643    0.048392    0.078214
             6         1.054197    1.418963    2.118922    0.977861

normits_v3.3_id        1001009     1001010   ...     11357010    11358001  \
purpose mode period                          ...
1       1    1       744.253770  951.084953  ...  1889.772885  282.410518
             2       295.638404  369.118210  ...   643.009899   93.654531
             3        15.777363   19.264924  ...    35.700821    3.355730
             4       182.326539  364.829438  ...   666.617591  109.128235
             5       100.653890  141.216421  ...   199.495916   22.463703
...                         ...         ...  ...          ...         ...
8       7    2         0.116594    0.123400  ...    12.740416    0.624892
             3         0.124936    0.132229  ...     6.152360    0.025823
             4         0.129551    0.137113  ...     0.485847    0.027818
             5         0.094336    0.099842  ...     7.456112    0.019339
             6         4.630000    2.426933  ...     0.366081    0.019034

normits_v3.3_id         11358002     11358003     11358004     11358005  \
purpose mode period
1       1    1       9915.151747  8318.745481  3828.723675  6108.462849
             2       3400.586358  2840.434078  1309.548982  2095.264502
             3        191.106189   158.465236    73.244997   117.773947
             4       3565.213071  2957.501932  1366.616749  2197.116072
             5       1060.032402   882.197944   407.245136   653.369273
...                          ...          ...          ...          ...
8       7    2         58.082901    51.955852    23.167322    35.836295
             3         29.753566    25.673376    11.608176    18.403922
             4          2.180456     1.956793     0.868786     1.346819
             5         33.805929    30.021157    13.339137    20.908088
             6          1.642951     1.474423     0.654621     1.014814

normits_v3.3_id         11358006     11358007     11358008     11358009
purpose mode period
1       1    1       9456.062670  8752.804144  4658.186790  7120.879139
             2       3275.988370  2994.745716  1592.240500  2437.071827
             3        186.883697   167.737521    88.991252   136.515931
             4       3481.909746  3131.912540  1660.575799  2547.756065
             5       1029.625619   931.336686   495.048746   758.469233
...                          ...          ...          ...          ...
8       7    2         48.629251    50.977124    28.603442    42.432648
             3         27.102671    25.683910    14.351610    21.429818
             4          1.803733     1.921795     1.076193     1.597795
             5         28.714063    29.846748    16.544507    24.727139
             6          1.359094     1.448053     0.810900     1.203922

[336 rows x 5430 columns]

In [66]:
hb_prod_tem.sum()

503459405.854709

In [12]:
normits = cb.ZoningSystem.get_zoning("normits")
hb_prod_tem = hb_prod_tem.aggregate_comp_zones(normits).aggregate(["p", "m", "tp"])

In [7]:
hb_prod_notem.index.names = hb_prod_tem.segmentation.naming_order
hb_prod_notem.columns.name = normits.column_name

In [14]:
hb_prod_check = hb_prod_notem / hb_prod_tem.data

In [15]:
hb_prod_check

normits_id  1001001   1001002   1001003   1001004   1001005   1001006   \
p m tp
1 1 1            1.0       1.0       1.0       1.0       1.0       1.0
    2            1.0       1.0       1.0       1.0       1.0       1.0
    3            1.0       1.0       1.0       1.0       1.0       1.0
    4            1.0       1.0       1.0       1.0       1.0       1.0
    5            1.0       1.0       1.0       1.0       1.0       1.0
...              ...       ...       ...       ...       ...       ...
8 7 2            1.0       1.0       1.0       1.0       1.0       1.0
    3            1.0       1.0       1.0       1.0       1.0       1.0
    4            1.0       1.0       1.0       1.0       1.0       1.0
    5            1.0       1.0       1.0       1.0       1.0       1.0
    6            1.0       1.0       1.0       1.0       1.0       1.0

normits_id  1001007   1001008   1001009   1001010   ...  11357010  11358001  \
p m tp                                              ...
1 1 1            1.0       1.0       1.0       1.0  ...       1.0       1.0
    2            1.0       1.0       1.0       1.0  ...       1.0       1.0
    3            1.0       1.0       1.0       1.0  ...       1.0       1.0
    4            1.0       1.0       1.0       1.0  ...       1.0       1.0
    5            1.0       1.0       1.0       1.0  ...       1.0       1.0
...              ...       ...       ...       ...  ...       ...       ...
8 7 2            1.0       1.0       1.0       1.0  ...       1.0       1.0
    3            1.0       1.0       1.0       1.0  ...       1.0       1.0
    4            1.0       1.0       1.0       1.0  ...       1.0       1.0
    5            1.0       1.0       1.0       1.0  ...       1.0       1.0
    6            1.0       1.0       1.0       1.0  ...       1.0       1.0

normits_id  11358002  11358003  11358004  11358005  11358006  11358007  \
p m tp
1 1 1            1.0       1.0       1.0       1.0       1.0       1.0
    2            1.0       1.0       1.0       1.0       1.0       1.0
    3            1.0       1.0       1.0       1.0       1.0       1.0
    4            1.0       1.0       1.0       1.0       1.0       1.0
    5            1.0       1.0       1.0       1.0       1.0       1.0
...              ...       ...       ...       ...       ...       ...
8 7 2            1.0       1.0       1.0       1.0       1.0       1.0
    3            1.0       1.0       1.0       1.0       1.0       1.0
    4            1.0       1.0       1.0       1.0       1.0       1.0
    5            1.0       1.0       1.0       1.0       1.0       1.0
    6            1.0       1.0       1.0       1.0       1.0       1.0

normits_id  11358008  11358009
p m tp
1 1 1            1.0       1.0
    2            1.0       1.0
    3            1.0       1.0
    4            1.0       1.0
    5            1.0       1.0
...              ...       ...
8 7 2            1.0       1.0
    3            1.0       1.0
    4            1.0       1.0
    5            1.0       1.0
    6            1.0       1.0

[336 rows x 5430 columns]

In [24]:
# hb_attr_tem = cb.DVector.load(r"E:\tem\outputs\exp_seg\Core\hb_attractions\hb_normits_tem_segmented_2023_dvec.h5")
hb_attr_notem = (
    hb_notem["attr"]
    .groupby(level=["normits_v3.3_id", "purpose", "mode", "period"])
    .sum()
    .unstack(level="normits_v3.3_id")
)

In [31]:
hb_attr_notem.groupby(["mode", "period", "purpose"]).sum()

normits_v3.3_id         1001001       1001002       1001003     1001004   \
mode period purpose
1    1      1         117.466537  1.659545e+02  1.378546e+03  267.021020
            2           1.669958  2.401309e+00  1.932575e+01    3.610760
            3        1975.785510  3.951571e+03  5.516643e+03  395.157102
            4          95.035818  1.839817e+02  3.266315e+03  112.709652
            5          48.512882  4.734005e+01  5.790239e+02  149.665646
...                          ...           ...           ...         ...
7    6      4           0.316361  6.124489e-01  1.087310e+01    0.375195
            5           0.000860  8.396376e-04  1.026975e-02    0.002655
            6           0.281978  2.819782e-01  2.108228e+00    0.889994
            7           0.007158  5.792672e-03  5.571487e-03    0.004339
            8           0.322628  4.872439e-13  3.840671e-13    0.289635

normits_v3.3_id          1001005       1001006     1001007       1001008   \
mode period purpose
1    1      1        9.799368e+01  3.974695e+02  586.939502  6.050446e+01
            2        1.460991e+00  5.522167e+00    8.105553  8.619507e-01
            3        3.951571e+03  2.272153e+03  790.314204  8.891035e+02
            4        6.851272e+01  1.482086e+02  497.776141  1.209984e+02
            5        1.119528e+01  1.184047e+02   87.753848  3.221662e+01
...                           ...           ...         ...           ...
7    6      4        2.280692e-01  4.933655e-01    1.657026  4.027865e-01
            5        1.985629e-04  2.100063e-03    0.001556  5.714038e-04
            6        2.819782e-01  9.516764e-01    1.856356  4.833912e-01
            7        4.815473e-03  4.970768e-03    0.004917  5.611885e-03
            8        3.538922e-13  3.853407e-13    1.542633  4.079131e-13

normits_v3.3_id         1001009      1001010   ...      11357010  \
mode period purpose                            ...
1    1      1         376.219218  1078.353423  ...  9.434693e+02
            2           5.370354    15.252200  ...  1.239326e+01
            3        3605.808555  5137.042325  ...  8.511043e+03
            4           0.000000  2172.522011  ...  1.831895e+03
            5         167.012861   485.737635  ...  3.925865e+02
...                          ...          ...  ...           ...
7    6      4           0.000000     7.232019  ...  3.898011e-02
            5           0.002962     0.008615  ...  6.604841e-01
            6           0.775440     3.242749  ...  7.082237e+00
            7           0.009329     0.008189  ...  3.763429e+00
            8           0.540462     3.778409  ...  6.908280e-15

normits_v3.3_id          11358001      11358002      11358003      11358004  \
mode period purpose
1    1      1        1.517723e+02   6962.046464   6123.470871  4.164842e+03
            2        1.508316e+00     92.227733     79.019180  5.339279e+01
            3        4.451880e+02  84533.952503  26401.012803  1.483022e+04
            4        5.911979e+01   6507.258410  10044.025637  6.982618e+03
            5        6.183483e+01   4967.034055   2292.859242  1.689051e+03
...                           ...           ...           ...           ...
7    6      4        7.478061e-04      0.138465      0.213722  1.485801e-01
            5        2.137532e-03      8.356494      3.857486  2.841644e+00
            6        4.993125e-16     38.552819     27.606592  1.402225e+01
            7        1.516886e-03     16.681302     14.762162  6.515635e+00
            8        9.476138e-04      0.021579      0.007094  1.353652e-14

normits_v3.3_id          11358005       11358006      11358007     11358008  \
mode period purpose
1    1      1         2960.895357   37281.041958   3756.722213  2089.088483
            2           39.105564     497.901695     48.769380    27.144450
            3        17616.994687  123866.084025  26176.236373  9112.546451
            4         3365.879663   24700.248418   5422.237649  6476.996659
            5         1205.765373   28277.076644   2067.272071  1096.342337
...                           ...            ...           ...          ...
7    6      4            0.071621       0.525586      0.115377     0.137821
            5            2.028569      47.573100      3.477960     1.844477
            6           19.341539     215.632581     30.627551    16.755772
            7           10.260513      13.858543     14.695343     7.945670
            8            0.009926       0.357520      0.003204     0.005172

normits_v3.3_id          11358009
mode period purpose
1    1      1        12410.646228
            2          162.222304
            3        28901.066439
            4         9910.153408
            5         9191.440461
...                           ...
7    6      4            0.210874
            5           15.463597
            6           77.641048
            7           12.080885
            8            0.044192

[336 rows x 5430 columns]

In [17]:
hb_attr_tem = hb_attr_tem.aggregate_comp_zones(normits).aggregate(["p", "m", "tp"])

In [18]:
hb_attr_notem.index.names = hb_attr_tem.segmentation.naming_order
hb_attr_notem.columns.name = normits.column_name

In [23]:
hb_attr_notem.groupby("p").sum()

normits_id,1001001,1001002,1001003,1001004,1001005,1001006,1001007,1001008,1001009,1001010,...,11357010,11358001,11358002,11358003,11358004,11358005,11358006,11358007,11358008,11358009
p,,,,,,,,,,,,,,,,,,,,,
1,6618.967052,11043.500288,36688.948891,4981.217224,9979.677576,9842.824094,10914.766161,3710.073605,12917.773313,33129.437967,...,34476.238223,2963.534124,277049.150549,150198.136800,93978.617846,81946.038134,779494.537893,117813.172815,62847.590838,238789.401955
2,5295.145507,6344.646960,41258.017404,5622.261592,4795.662361,6869.986555,12805.457059,4036.443796,8486.402509,38610.636363,...,30801.954447,2393.427957,189061.993333,149347.564411,94537.150549,71246.999039,640830.573614,107523.522022,83410.754205,220159.308389
3,2289.125155,2260.248647,15051.971385,3386.001693,1765.614306,3717.858439,7282.640305,2235.043329,4076.194334,16695.711374,...,12411.505446,888.414680,66712.750770,57294.183431,33567.850718,31291.140767,275306.670686,47189.547261,32652.178005,99691.140385
4,1214.438692,1300.516547,9608.174768,2170.201473,919.364544,2677.524700,4949.084540,971.004449,2806.544197,10270.732134,...,7755.130531,786.942964,48306.689484,41130.900427,25593.468230,21761.096892,233655.348145,30286.690480,19231.414784,79253.010019
5,2955.204394,2711.679921,18000.086055,3395.033207,1940.984218,3626.581676,7569.400705,2532.133534,4495.214964,19155.333412,...,15080.793013,1258.921847,73685.095257,72531.178840,43459.682177,36895.115407,280524.398625,55138.219052,41803.926776,105626.016599
6,2302.199934,1944.675506,11838.458540,2816.316712,1453.028074,2861.656515,6421.621557,1919.767287,3735.568357,15204.424480,...,11566.649848,985.129863,60116.712264,55668.914435,33263.194006,28934.821754,240046.068153,43041.816538,31634.608205,87168.862337

In [22]:
hb_attr_tem.aggregate(["p"]).data

normits_id,1001001,1001002,1001003,1001004,1001005,1001006,1001007,1001008,1001009,1001010,...,11357010,11358001,11358002,11358003,11358004,11358005,11358006,11358007,11358008,11358009
p,,,,,,,,,,,,,,,,,,,,,
1,1776.104247,2531.497750,20698.752390,3937.643211,1517.657139,5940.722378,8747.134913,915.864042,5699.956045,16264.072633,...,14663.676260,1959.523036,108580.527009,94337.798110,63921.667112,46110.193527,583450.838143,58002.958889,32318.510537,192348.942297
2,222.468583,323.984649,2551.223140,469.282363,201.039377,727.243318,1060.822881,114.677480,717.865141,2021.664412,...,1632.397809,337.358663,12230.118701,10276.386655,6914.679784,5174.664756,66441.197006,6375.475235,3544.715423,21301.299746
3,11345.713903,12689.541601,24325.271455,10270.651745,12689.541601,11547.288058,10539.417284,10606.608669,12454.371754,13495.838219,...,15716.432702,10381.845336,88188.134169,37755.869190,19959.302438,31875.197199,114476.698193,27577.325701,16120.298589,29406.850973
4,11621.717910,12299.969301,46701.157343,11756.488724,11419.467502,12027.183910,14692.791325,11819.693992,10897.027686,27463.470664,...,25146.269957,11275.397090,83307.242469,99920.659663,65210.728674,47975.265776,224819.877200,53073.444838,61277.798626,87982.318156
5,5229.418098,5229.642850,12834.657917,5731.210018,5051.058703,5576.181676,5425.043878,5154.351486,5812.589453,7374.608755,...,6735.697262,5326.645529,37069.259802,20143.345828,12521.973865,15343.190398,141488.862152,14135.857416,9856.471092,46141.021420
6,8598.534488,8598.534488,23193.350024,10959.409765,8598.534488,11198.918851,14711.718781,9380.604973,10514.607177,20094.970621,...,15046.111980,7503.635808,63569.078829,44407.875987,22437.117174,35605.719569,252156.359089,40121.516804,25348.280559,90190.183127
7,6905.263932,5588.460563,5375.073019,4185.913335,4645.711594,4795.531390,4743.873940,5414.047182,9000.307345,7899.934220,...,18468.273401,2709.130287,81860.140785,72442.347842,31974.172315,50351.407041,68008.019321,72114.447449,38991.781533,59284.516745
8,5207.856677,4382.885269,8765.770538,5123.494770,4382.885269,4382.885269,7897.194887,4382.885269,5614.124875,12990.569301,...,4382.885269,4864.862316,16214.173982,9786.463536,4382.885269,10175.898658,63990.807732,4850.940213,5130.615655,10673.877040

In [28]:
hb_attr_tem.aggregate(["m", "tp"]).data

normits_id     1001001      1001002       1001003      1001004      1001005   \
m tp
1 1         5371.506919  5824.082130  13338.282634  5152.499734  5675.759425
  2         4434.029265  4438.639756  12121.651663  4408.620030  4233.088589
  3         1423.966049  1342.541285   3628.866626  1459.361599  1274.516420
  4          709.750301   667.802240   1997.072117   805.650147   624.425995
  5         1725.669759  1611.592524   4101.711778  1620.766876  1501.167715
  6         1382.123216  1284.421239   3163.417493  1398.978530  1236.423815
2 1          254.813130   280.123011    883.403225   279.198728   261.137708
  2          247.465959   234.423102    669.025740   245.681183   216.385068
  3          126.314100   115.400312    262.518582   125.974050   109.287023
  4           67.231375    72.186864    362.240926    97.069291    57.357496
  5          150.820201   142.288602    448.954702   152.550945   130.047133
  6          111.762896   106.135271    312.746421   118.826214    97.517441
3 1         7638.614001  8362.235751  24334.476737  8141.955137  7816.091529
  2         8546.132412  8627.307515  24864.509217  8613.045469  8058.560535
  3         3963.449409  3931.874259  11372.056147  4324.639844  3691.216630
  4         1689.266167  1812.051318   7558.865055  2207.560074  1564.966710
  5         4857.733859  4719.567616  13280.794397  4913.221211  4372.936888
  6         4052.959339  3882.719409  10307.841599  4074.261389  3615.691121
4 1          158.637866   177.580750    777.410060   202.407353   148.616124
  2          128.931232   122.056257    307.622908   129.576777   114.279689
  3           77.723171    75.561576    232.401251    80.539270    69.548084
  4           57.070971    65.158056    336.391304    81.347852    50.058400
  5          112.070232   105.669681    270.206135   105.041186    93.741626
  6           79.338961    74.194183    190.684753    83.061210    68.817778
5 1          990.759344  1055.484500   2859.824657   988.062185  1025.803015
  2          874.981522   869.385265   2369.720159   875.858961   825.566739
  3          100.961545   102.736435    282.495403   111.436518   100.067235
  4           55.531070    61.793655    287.044819    77.917067    51.444975
  5          274.411787   274.356620    802.774314   289.007494   258.638280
  6          151.285992   148.871108    399.562139   160.966435   140.484870
6 1          288.049596   277.240563    692.287530   300.322183   269.543560
  2          146.394179   142.938513    334.779210   146.356767   138.520244
  3           60.284362    59.423858    125.722832    61.883890    58.619668
  4           28.484638    29.179591     97.870445    32.708251    26.417648
  5          123.386265   110.335262    205.791841   109.910320   104.259987
  6           50.870977    47.867609     97.065395    49.374613    46.516148
7 1           95.257784    95.503856    197.131317    96.323148    95.164001
  2           86.075953    86.848055    202.812172    87.221303    85.587582
  3           31.562711    31.716542     68.858000    32.137037    31.471026
  4           21.280152    21.808025     55.421642    22.982523    21.072371
  5           55.532843    55.700016    117.294239    56.201569    55.442803
  6           38.877207    39.008376     86.180778    39.716600    38.624349

normits_id     1001006       1001007      1001008      1001009       1001010   \
m tp
1 1         5702.463186   5941.079670  4985.581158  6138.154796   8671.343230
  2         4517.522226   5471.859550  4183.844245  4874.326653   8742.817931
  3         1461.247065   1953.573300  1349.975347  1641.825751   3108.056196
  4          822.533957   1221.666732   635.388620   915.228982   1998.752523
  5         1630.483239   2108.194813  1570.813834  1939.305361   3456.142398
  6         1361.937194   1887.490405  1279.132153  1547.645718   2942.541061
2 1          322.710776    376.266868   232.786966   329.359309    586.499527
  2          250.506204    339.439643   222.279991   290.350405    577.401409
  3          126.316801    172.138759   115.269073   151.150343    265.544010
  4          120.742798    177.666284    53.351594   124.404681    311.949592
  5          154.738513    226.189848   133.610660   177.919470    404.619406
  6          123.658596    172.377139    98.473909   140.578551    282.945320
3 1         9396.023870  10712.525860  6977.390978  9856.555521  16933.040018
  2         9054.069161  10719.240356  8139.774001  9750.682572  17738.660997
  3         4566.279757   5745.517549  3894.841400  4819.469465   9035.308060
  4         2632.351303   3548.332987  1541.445400  2646.624831   5962.858960
  5         5148.697040   6360.454561  4630.531414  5698.608695  10232.158877
  6         4233.394304   5276.832873  3835.982726  4782.993275   8340.020216
4 1          253.181708    328.429286   134.125755   259.625207    576.001538
  2          131.809565    168.290709   116.418236   153.699335    265.615507
  3           83.703135    108.588941    74.844433    91.576068    186.125564
  4          108.758255    149.219374    43.262528   113.108620    265.251227
  5          116.627801    139.029524    98.717423   145.072635    224.124105
  6           87.079431    115.860113    73.792844   101.229743    182.009746
5 1         1078.723905   1130.818464   936.568252  1122.417791   1524.981423
  2          910.152019   1039.790797   833.536224   977.044318   1516.396730
  3          115.035936    135.389742   102.667327   111.722875    185.834268
  4           96.134335    128.219160    47.686843    93.544063    211.088451
  5          301.933925    365.111308   266.842398   311.051070    554.979282
  6          169.279620    205.758410   144.186957   179.787988    297.600421
6 1          300.103810    393.668345   266.588552   325.749154    568.817185
  2          149.005593    172.255994   139.931046   160.542064    229.503592
  3           62.406761     66.957483    59.923698    64.523636     78.041193
  4           37.164517     47.548890    25.069162    39.246357     72.456715
  5          109.013469    139.448041   108.909705   141.831655    207.679255
  6           49.129022     58.983313    47.801660    55.962573     78.425602
7 1           97.020981     98.480044    95.085022    96.844086    101.796770
  2           88.043001     92.771037    86.263878    86.887475    110.552902
  3           32.380225     33.368599    31.561887    32.175431     36.618929
  4           24.418276     26.643632    20.698575    24.178064     32.284134
  5           56.475210     57.640385    55.559390    56.230463     61.215342
  6           40.102719     42.321160    38.679075    39.962121     47.814332

normits_id  ...      11357010     11358001      11358002      11358003  \
m tp        ...
1 1         ...   8663.771624  4833.203264  47260.272602  27585.870089
  2         ...   7695.885798  3931.256452  36208.440452  27197.219153
  3         ...   2495.078576  1146.013960  10835.373104   8569.622633
  4         ...   1381.729195   626.835899   7191.858831   5611.251543
  5         ...   2816.336990  1334.745012  11352.319191  10100.237836
  6         ...   2145.447488  1191.769264   8802.474755   7311.769355
2 1         ...    361.158373   222.317925   2070.766472   1280.321129
  2         ...    266.087317   191.869997   1138.474330    817.246482
  3         ...    163.125909    96.139528    678.257985    518.443571
  4         ...    118.733228    45.130528    634.109267    553.605294
  5         ...    182.211574   119.308644    765.826602    597.528984
  6         ...    159.027245    88.362417    721.069500    569.484764
3 1         ...  16021.713276  7053.756828  87822.016582  65723.933346
  2         ...  16737.156611  7501.268811  72630.201784  62622.729275
  3         ...   8644.462829  3305.553271  38590.809507  32474.468798
  4         ...   5390.581487  1528.332561  30112.828858  25646.006148
  5         ...  10638.628495  4008.624499  45787.718628  40476.865065
  6         ...   8617.957889  3280.194224  37835.532527  32880.092146
4 1         ...    523.352219   185.180986   3358.787264   2767.716298
  2         ...    180.526139   121.173452    799.430777    641.000396
  3         ...    130.506780    69.645459    546.167360    462.716806
  4         ...    248.588365    63.755922   1633.187387   1398.928004
  5         ...    176.458147    92.926502    866.789334    738.074096
  6         ...    154.942267    61.328090    700.403838    574.285063
5 1         ...   2113.721972   914.680842  14680.218749   8263.444856
  2         ...   2078.262456   745.471740  10760.375861   8226.986556
  3         ...    250.055415    93.345384   1223.089134    972.832731
  4         ...    401.636440    44.323599   2686.745206   2353.293264
  5         ...    789.884579   234.897630   3604.987823   3309.185480
  6         ...    499.463074   127.379479   2508.310028   2145.195952
6 1         ...    832.587257   256.537263   5438.824366   4062.145193
  2         ...    381.394642   132.893881   2049.201041   1557.699049
  3         ...    191.713097    56.481977    914.651345    691.965438
  4         ...    156.817532    24.775284   1003.623214    857.089777
  5         ...    283.119558    84.579875   1263.420504   1054.325973
  6         ...    169.521426    43.114229    759.115943    645.671350
7 1         ...    114.288007    94.658682    483.711925    302.137728
  2         ...    142.597737    83.934143    679.495565    490.929387
  3         ...     48.194764    31.288980    186.920206    139.811889
  4         ...     36.917068    20.703196    149.568751    107.485216
  5         ...     75.535547    55.285970    267.029390    206.543416
  6         ...     50.038444    38.069918    183.887761    132.693117

normits_id      11358004      11358005       11358006      11358007  \
m tp
1 1         16103.678912  18984.825026  106333.341156  18856.771920
  2         15942.752637  17005.451269   91391.557874  18022.689726
  3          4523.527844   5933.221584   29681.367435   6709.354933
  4          3263.489309   3586.632627   29657.807462   4023.587580
  5          5564.201807   6519.357892   27474.629988   7236.631136
  6          4041.645532   4955.932630   25271.930890   5076.056825
2 1           777.200468    853.243969    5790.976515    785.322803
  2           437.808615    615.664501    2837.916473    543.384741
  3           256.701380    398.772675    1694.119106    407.705417
  4           337.044724    318.150890    2542.757847    375.344984
  5           323.573606    430.896481    2170.491701    407.990948
  6           320.711313    387.507380    2329.054122    399.299223
3 1         40808.087761  39593.173647  318620.761660  43678.726225
  2         36669.612290  38211.256526  210638.270015  44011.756220
  3         18167.434167  20813.987329  123948.867729  25295.787427
  4         15775.060700  14554.307846  129874.471026  18082.719810
  5         22476.306942  25453.077180  127284.922694  31042.424332
  6         18335.199902  20700.843819  108295.924870  25175.620011
4 1          1799.701313   1490.426331   15695.494144   1777.944929
  2           374.067633    425.474508    2497.486919    432.352395
  3           255.080411    305.074850    1548.228507    353.532476
  4           905.801253    736.661920    7802.060496    913.808369
  5           429.000248    454.103933    2890.032279    532.742355
  6           299.474725    393.121642    1805.568554    475.150359
5 1          5047.186666   5154.451459   38984.803419   5415.331406
  2          4794.323487   4969.911965   28832.258251   5817.519352
  3           582.776528    579.558104    4306.117343    684.503238
  4          1562.193103   1184.385875   13312.518392   1492.491780
  5          1962.616019   1911.892958   12017.699472   2344.509601
  6          1242.304178   1285.826525    8311.804767   1600.127424
6 1          2622.150815   2255.216266   22365.108319   2501.797864
  2           910.349817    936.871425    6458.727495   1083.182558
  3           363.650031    488.990164    3691.544046    625.997178
  4           552.782441    458.285766    4807.710604    559.093857
  5           533.133324    725.746636    3068.075837    890.501078
  6           325.947794    439.012950    1791.102198    544.516869
7 1           168.194041    246.263315     976.818080    171.622352
  2           291.750716    321.586224    1802.895577    296.877736
  3            73.749883    109.546630     482.538082    100.030324
  4            51.345331     86.493794     238.952831     87.793411
  5           110.194651    162.992114     512.136530    132.134823
  6            70.048501    110.269523     409.520022     87.261505

normits_id      11358008       11358009
m tp
1 1         12469.052265   33076.416051
  2         14714.402608   31244.580007
  3          4748.726570   10823.988467
  4          2659.473380    9577.262656
  5          5561.918852   10545.629336
  6          3960.436653    8641.817652
2 1           521.510727    1796.207644
  2           412.270150     906.830546
  3           267.221056     601.885870
  4           241.372895     873.548181
  5           302.443076     707.490413
  6           278.583694     789.841965
3 1         27481.216538  105563.710414
  2         33380.945438   78902.941856
  3         17353.406699   47150.387963
  4         11308.186499   45213.988490
  5         21935.930253   50951.482029
  6         17688.549768   42552.779291
4 1          1057.542354    5204.930502
  2           308.395581     885.067737
  3           254.269120     604.140259
  4           525.085846    2629.681406
  5           340.376797    1067.748496
  6           290.857853     740.840625
5 1          3381.151131   11966.405410
  2          4208.701798   10495.448528
  3           529.297362    1511.997747
  4           872.009525    4521.953183
  5          1698.217387    4542.304669
  6          1028.802396    3123.695932
6 1          1581.808807    7192.651635
  2           796.301447    2148.736615
  3           371.325005    1347.833518
  4           320.721868    1618.468624
  5           547.655476    1256.714384
  6           332.797322     739.323800
7 1           142.178624     311.845642
  2           244.089306     598.522312
  3            71.391613     175.259151
  4            56.643848     105.725780
  5           107.747589     190.761844
  6            65.001339     148.306146

[42 rows x 5430 columns]

In [57]:
hb_attr_tem.data.groupby(level="p").sum() / hb_attr_notem.groupby(level="p").sum()

normits_id,1001001,1001002,1001003,1001004,1001005,1001006,1001007,1001008,1001009,1001010,...,11357010,11358001,11358002,11358003,11358004,11358005,11358006,11358007,11358008,11358009
p,,,,,,,,,,,,,,,,,,,,,
1,1.008964,0.998533,1.017945,1.046012,0.980275,1.025765,1.028368,1.006078,1.006812,1.011235,...,0.994312,0.997141,0.990827,1.005917,1.011655,0.992717,0.987160,1.004066,0.999391,0.998487
2,1.007521,1.004413,1.010580,1.022400,0.999046,1.014022,1.014522,1.006006,1.006968,1.007928,...,0.992688,0.992520,0.991872,0.997074,0.999628,0.992544,0.990922,0.996816,0.994126,0.994459
3,0.983136,0.983136,1.003269,0.983136,0.983136,0.983136,0.983136,0.983136,0.983136,0.983136,...,0.977014,0.963371,1.001929,0.978517,0.977014,0.980753,0.992838,0.977014,0.977014,0.977014
4,0.990455,0.990455,0.990455,0.990455,0.990455,0.990455,0.990455,0.990455,inf,0.990455,...,0.989160,0.974367,0.989160,0.989160,0.989160,0.989160,0.989160,0.989160,0.989160,0.989160
5,0.991837,0.991837,0.991837,0.991837,0.991837,0.991837,0.991837,0.991837,0.991837,0.991837,...,0.996829,0.971066,0.996829,0.996829,0.996829,0.996829,0.996829,0.996829,0.996829,0.996829
6,0.982350,0.982350,0.982350,0.982350,0.982350,0.982350,0.982350,0.982350,0.982350,0.982350,...,0.995638,0.978582,0.995638,0.995638,0.995638,0.995638,0.995638,0.995638,0.995638,0.995638
7,0.987687,0.987687,0.987687,0.987687,0.987687,0.987687,0.987687,0.987687,0.987687,0.987687,...,0.982121,0.975789,0.982121,0.982121,0.982121,0.982121,0.982121,0.982121,0.982121,0.982121
8,1.005308,1.005308,1.005308,1.005308,1.005308,1.005308,1.005308,1.005308,1.005308,1.005308,...,0.967409,0.976736,0.967409,0.967409,0.967409,0.967409,0.967409,0.967409,0.967409,0.967409

In [33]:
nhb_notem = pd.read_csv(
    r"I:\NorMITs NoTEM\voa_gb_2023_uni\tripend\NorMITs_tripend_2023_nhb.csv.bz2",
    index_col=[0, 1, 2, 3, 4, 5],
)
nhb_tem_attr = cb.DVector.load(
    r"E:\tem\outputs\exp_seg\Core\nhb_attractions\nhb_normits_tem_segmented_2023_dvec.h5"
)

In [34]:
nhb_notem.groupby(["normits_v3.3_id", "purpose"])["prod"].sum().unstack(
    level="normits_v3.3_id"
)

normits_v3.3_id,1001001,1001002,1001003,1001004,1001005,1001006,1001007,1001008,1001009,1001010,...,11357010,11358001,11358002,11358003,11358004,11358005,11358006,11358007,11358008,11358009
purpose,,,,,,,,,,,,,,,,,,,,,
1,543.112338,808.993593,3037.197548,540.486675,701.931551,892.697439,1184.277958,343.940289,1094.063639,3007.563820,...,2746.248944,240.429817,17886.417850,13437.196108,8494.405307,7012.037300,68466.309475,9965.776022,5963.711732,23142.336012
2,185.099296,259.736631,1786.458235,313.512048,179.299076,474.686207,712.284259,112.210692,487.051867,1499.677082,...,1277.939776,196.064376,9308.284500,7429.490111,4907.093196,3798.713966,45340.318278,4888.104541,2713.524864,14706.095675
3,493.478993,790.733248,1704.658560,263.737138,744.823119,586.957000,521.000883,280.459552,872.791551,1746.817575,...,2153.449229,216.338014,16295.740347,8018.596386,4591.705745,4893.844406,33543.169689,7234.243649,3405.672240,10482.230660
4,1643.089929,1826.422400,10482.852471,1826.407068,1385.072194,2211.725219,3738.487299,1313.241861,2728.395831,10115.429582,...,9402.182328,738.128855,54282.854991,44876.468264,27741.424420,22799.671721,198866.514841,34129.070089,24006.521773,71123.406389
5,324.154631,376.415172,2346.957897,419.107681,276.328363,493.662713,771.308973,256.879269,597.323793,2191.603640,...,2086.355362,198.108185,13136.079665,10187.706921,6445.981333,5145.551507,52339.998439,7809.425537,5375.254581,18371.200696
6,1173.344740,1169.361253,5048.357452,1331.084365,956.099234,1549.105458,2602.063437,1004.184452,1971.636077,5909.353614,...,5958.052126,471.752682,34679.195506,26510.240505,15207.307844,15215.455361,120578.376390,22577.044400,13969.146170,43900.710198
7,1809.613216,1786.485671,5834.324646,1544.735897,1466.400192,1886.198894,2647.263595,1447.188677,2725.133205,6268.974058,...,7217.047598,737.448781,38644.379286,31521.051312,17599.450660,18129.926627,107869.875638,26819.879781,16896.750366,42987.223093
8,748.236842,496.667712,1880.214009,700.659369,397.143912,581.270863,1975.410147,427.247112,1186.088972,4718.742662,...,1831.874377,543.208298,10629.182092,8419.569997,4529.895683,5128.322132,42802.973830,7135.639410,4525.823403,13625.019556

In [35]:
nhb_tem_prod.aggregate(["p"]).aggregate_comp_zones(normits).data

normits_id,1001001,1001002,1001003,1001004,1001005,1001006,1001007,1001008,1001009,1001010,...,11357010,11358001,11358002,11358003,11358004,11358005,11358006,11358007,11358008,11358009
p,,,,,,,,,,,,,,,,,,,,,
11,543.239153,809.165330,3038.113888,540.670315,702.056151,892.978727,1184.591887,344.023127,1094.369030,3008.178826,...,2746.486721,240.458928,17892.554488,13438.440052,8495.185764,7012.759834,68478.722984,9966.706875,5964.292786,23145.114834
12,185.224146,259.933723,1787.317286,313.675513,179.457344,474.968070,712.643287,112.274024,487.370583,1500.451036,...,1278.179157,196.129636,9311.151717,7431.120007,4908.149725,3799.554049,45351.534429,4889.080449,2714.134160,14709.444897
13,493.538424,790.823989,1705.024303,263.769354,744.907443,587.026399,521.062389,280.492157,872.896453,1747.009298,...,2153.585533,216.365317,16310.975738,8019.328990,4591.962407,4894.590591,33558.618980,7234.707180,3405.878307,10482.912344
14,1643.451414,1826.715830,10484.072301,1826.748738,1385.297085,2212.075316,3739.183920,1313.454324,2729.014414,10117.086786,...,9402.838346,738.185156,54300.418435,44879.765314,27743.189073,22801.833907,198897.842288,34131.580579,24008.183587,71129.000069
15,324.237657,376.482694,2347.321353,419.205531,276.375694,493.753675,771.489496,256.923043,597.484703,2192.096143,...,2086.667149,198.148578,13140.682726,10189.523510,6447.274130,5146.492581,52360.696056,7810.923090,5376.151212,18377.457809
16,1173.733611,1169.664646,5048.986080,1331.362592,956.347053,1549.388655,2602.615629,1004.426236,1972.216602,5910.612212,...,5959.214634,471.820712,34693.466258,26515.770055,15210.181075,15219.112921,120617.205881,22581.765344,13971.911312,43910.621273
17,1810.271627,1787.065049,5835.707687,1545.161004,1466.868360,1886.709874,2647.904796,1447.673514,2726.032494,6270.418384,...,7217.353658,737.408857,38650.657673,31522.395598,17600.137123,18130.810565,107877.164611,26821.035924,16897.459999,42988.853101
18,748.720173,496.890391,1880.752918,701.057257,397.317362,581.509764,1976.788172,427.428883,1186.858087,4721.971956,...,1832.197339,543.187595,10633.976373,8421.152764,4530.408447,5129.739510,42826.544931,7137.058156,4526.832466,13628.706154